[build]
builder = "nixpacks"
buildCommand = "dotnet publish MangaBot.csproj -c Release -o out"

[deploy]
startCommand = "dotnet out/MangaBot.dll"
healthcheckPath = "/health"

[phases.setup]
nixPkgs = ["dotnet-sdk_8", "icu", "zlib"]

[phases.install]
cmds = ["dotnet restore MangaBot.csproj --no-cache"]

[phases.build]
cmds = ["dotnet publish MangaBot.csproj -c Release -o out"]

[phases.setup]
nixPkgs = ["dotnet-sdk_8"] 