[build]
builder = "nixpacks"
buildCommand = "dotnet publish MangaBot.csproj -c Release -o out"

[deploy]
startCommand = "dotnet out/MangaBot.dll"
healthcheckPath = "/health"

[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore MangaBot.csproj"]

[phases.build]
cmds = ["dotnet publish MangaBot.csproj -c Release -o out"] 